# Generated by Django 5.0 on 2024-01-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_percentage_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='percentage_completion',
        ),
    ]
